#!/usr/bin/env bash
# Creates a placeholder lib/amplify_outputs.dart when none exists, so that
# `flutter analyze` and `flutter test` compile with NO AWS credentials and no
# backend (cicd-pipeline.md, "Backend-outputs stub"). The real file is generated
# by `ampx sandbox --outputs-format dart --outputs-out-dir lib` (local
# development) or `ampx generate outputs --branch production ... --format dart
# --out-dir lib` (release) and is git-ignored. This script never overwrites an
# existing file.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$ROOT/lib/amplify_outputs.dart"

if [[ -f "$TARGET" ]]; then
  echo "stub_amplify_outputs: $TARGET already exists — leaving it untouched."
  exit 0
fi

cat > "$TARGET" <<'DART'
// STUB — generated by tool/stub_amplify_outputs.sh for CI / offline builds.
// Replace with the real outputs: `ampx sandbox --outputs-format dart --outputs-out-dir lib`.
const amplifyConfig = '{}';
DART

echo "stub_amplify_outputs: wrote placeholder $TARGET"
